"""add narrative columns to ai_reports

Revision ID: 484b917a3695
Revises: fcb8284c1309
Create Date: 2026-05-07 17:13:18.521984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484b917a3695'
down_revision: Union[str, None] = 'fcb8284c1309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_reports', sa.Column('paragraphs', sa.JSON(), nullable=True))
    op.add_column('ai_reports', sa.Column('recommendation', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_reports', 'recommendation')
    op.drop_column('ai_reports', 'paragraphs')
    # ### end Alembic commands ###
