"""add diagnosis_detail and diagnosis_keywords to ai_reports

Revision ID: 992b30f6fc50
Revises: 484b917a3695
Create Date: 2026-05-11 17:49:47.424101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '992b30f6fc50'
down_revision: Union[str, None] = '484b917a3695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_reports', sa.Column('diagnosis_detail', sa.Text(), nullable=True))
    op.add_column('ai_reports', sa.Column('diagnosis_keywords', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_reports', 'diagnosis_keywords')
    op.drop_column('ai_reports', 'diagnosis_detail')
    # ### end Alembic commands ###
