"""add read_at to ai_reports

Revision ID: 9e0473f1319e
Revises: 992b30f6fc50
Create Date: 2026-05-11 18:14:15.484028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0473f1319e'
down_revision: Union[str, None] = '992b30f6fc50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_reports', sa.Column('read_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_reports', 'read_at')
    # ### end Alembic commands ###
