"""add sync fields (client_id updated_at deleted_at)

Revision ID: a05ffd1de798
Revises: e750432a0e75
Create Date: 2026-05-01 08:31:48.081251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05ffd1de798'
down_revision: Union[str, None] = 'e750432a0e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diaries', sa.Column('client_id', sa.String(), nullable=False))
    op.add_column('diaries', sa.Column('emotion_tags', sa.JSON(), nullable=True))
    op.add_column('diaries', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('diaries', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_diaries_client_id'), 'diaries', ['client_id'], unique=False)
    op.create_index(op.f('ix_diaries_updated_at'), 'diaries', ['updated_at'], unique=False)
    op.create_unique_constraint('uq_diaries_user_client', 'diaries', ['user_id', 'client_id'])
    op.add_column('habit_logs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_habit_logs_updated_at'), 'habit_logs', ['updated_at'], unique=False)
    op.create_unique_constraint('uq_habit_logs_habit_date', 'habit_logs', ['habit_id', 'date'])
    op.add_column('habits', sa.Column('client_id', sa.String(), nullable=False))
    op.add_column('habits', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('habits', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_habits_client_id'), 'habits', ['client_id'], unique=False)
    op.create_index(op.f('ix_habits_updated_at'), 'habits', ['updated_at'], unique=False)
    op.create_unique_constraint('uq_habits_user_client', 'habits', ['user_id', 'client_id'])
    op.add_column('personality_results', sa.Column('client_id', sa.String(), nullable=False))
    op.add_column('personality_results', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_personality_results_client_id'), 'personality_results', ['client_id'], unique=False)
    op.create_index(op.f('ix_personality_results_updated_at'), 'personality_results', ['updated_at'], unique=False)
    op.create_unique_constraint('uq_personality_user_client', 'personality_results', ['user_id', 'client_id'])
    op.add_column('schedules', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_schedules_updated_at'), 'schedules', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_updated_at'), table_name='schedules')
    op.drop_column('schedules', 'updated_at')
    op.drop_constraint('uq_personality_user_client', 'personality_results', type_='unique')
    op.drop_index(op.f('ix_personality_results_updated_at'), table_name='personality_results')
    op.drop_index(op.f('ix_personality_results_client_id'), table_name='personality_results')
    op.drop_column('personality_results', 'updated_at')
    op.drop_column('personality_results', 'client_id')
    op.drop_constraint('uq_habits_user_client', 'habits', type_='unique')
    op.drop_index(op.f('ix_habits_updated_at'), table_name='habits')
    op.drop_index(op.f('ix_habits_client_id'), table_name='habits')
    op.drop_column('habits', 'deleted_at')
    op.drop_column('habits', 'updated_at')
    op.drop_column('habits', 'client_id')
    op.drop_constraint('uq_habit_logs_habit_date', 'habit_logs', type_='unique')
    op.drop_index(op.f('ix_habit_logs_updated_at'), table_name='habit_logs')
    op.drop_column('habit_logs', 'updated_at')
    op.drop_constraint('uq_diaries_user_client', 'diaries', type_='unique')
    op.drop_index(op.f('ix_diaries_updated_at'), table_name='diaries')
    op.drop_index(op.f('ix_diaries_client_id'), table_name='diaries')
    op.drop_column('diaries', 'deleted_at')
    op.drop_column('diaries', 'updated_at')
    op.drop_column('diaries', 'emotion_tags')
    op.drop_column('diaries', 'client_id')
    # ### end Alembic commands ###
