"""add ondelete cascade to user fks

Revision ID: aae3e30999fe
Revises: a05ffd1de798
Create Date: 2026-05-01 09:03:28.064967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae3e30999fe'
down_revision: Union[str, None] = 'a05ffd1de798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ai_reports_user_id_fkey', 'ai_reports', type_='foreignkey')
    op.create_foreign_key(None, 'ai_reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('diaries_user_id_fkey', 'diaries', type_='foreignkey')
    op.create_foreign_key(None, 'diaries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('emotion_analyses_diary_id_fkey', 'emotion_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'emotion_analyses', 'diaries', ['diary_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('habit_logs_habit_id_fkey', 'habit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'habit_logs', 'habits', ['habit_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('habits_user_id_fkey', 'habits', type_='foreignkey')
    op.create_foreign_key(None, 'habits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('personality_results_user_id_fkey', 'personality_results', type_='foreignkey')
    op.create_foreign_key(None, 'personality_results', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('recommendation_logs_user_id_fkey', 'recommendation_logs', type_='foreignkey')
    op.create_foreign_key(None, 'recommendation_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('schedules_user_id_fkey', 'schedules', type_='foreignkey')
    op.create_foreign_key(None, 'schedules', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.create_foreign_key('schedules_user_id_fkey', 'schedules', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'recommendation_logs', type_='foreignkey')
    op.create_foreign_key('recommendation_logs_user_id_fkey', 'recommendation_logs', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'personality_results', type_='foreignkey')
    op.create_foreign_key('personality_results_user_id_fkey', 'personality_results', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'habits', type_='foreignkey')
    op.create_foreign_key('habits_user_id_fkey', 'habits', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'habit_logs', type_='foreignkey')
    op.create_foreign_key('habit_logs_habit_id_fkey', 'habit_logs', 'habits', ['habit_id'], ['id'])
    op.drop_constraint(None, 'emotion_analyses', type_='foreignkey')
    op.create_foreign_key('emotion_analyses_diary_id_fkey', 'emotion_analyses', 'diaries', ['diary_id'], ['id'])
    op.drop_constraint(None, 'diaries', type_='foreignkey')
    op.create_foreign_key('diaries_user_id_fkey', 'diaries', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'ai_reports', type_='foreignkey')
    op.create_foreign_key('ai_reports_user_id_fkey', 'ai_reports', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
