"""add feedback_ratings table

Revision ID: fcb8284c1309
Revises: aae3e30999fe
Create Date: 2026-05-01 14:42:55.659542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb8284c1309'
down_revision: Union[str, None] = 'aae3e30999fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('rating', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_ratings_created_at'), 'feedback_ratings', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_ratings_id'), 'feedback_ratings', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_ratings_user_id'), 'feedback_ratings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_ratings_user_id'), table_name='feedback_ratings')
    op.drop_index(op.f('ix_feedback_ratings_id'), table_name='feedback_ratings')
    op.drop_index(op.f('ix_feedback_ratings_created_at'), table_name='feedback_ratings')
    op.drop_table('feedback_ratings')
    # ### end Alembic commands ###
